[package]
name = "alonix"
version = "1.0.0"
authors = []

[addresses]
alonix5 = "1edeb16d379962ef569ff02272efbe948533f20cf7c70670f8f1b0da2d3a156c"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies]
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects" }


[dev-dependencies]
