[package]
name = "alonix"
version = "1.0.0"
authors = []

[addresses]
alonix = "ebd9983149940c8db441c3e3ad1a8a36d4647f8c599751c781180b40b45995b0"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies]
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects" }


[dev-dependencies]
